apiVersion: v1
kind: Namespace
metadata:
  name: knet-stress
  #labels:
    #istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: knet-stress
  namespace: knet-stress
  labels:
    app: knet-stress
spec:
  selector:
    app: knet-stress
  ports:
    - protocol: TCP
      name: web
      port: 6443
      targetPort: 6443
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: knet-stress
  namespace: knet-stress
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: knet-stress
  name: knet-stress
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: knet-stress
  namespace: knet-stress
subjects:
- kind: ServiceAccount
  name: knet-stress
  namespace: knet-stress
roleRef:
  kind: Role
  name: knet-stress
  apiGroup: ""
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: knet-stress
  namespace: knet-stress
  labels:
    app: knet-stress
spec:
  selector:
    matchLabels:
      app: knet-stress
  template:
    metadata:
      labels:
        app: knet-stress
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "6443"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - args:
        - server
        - --connection-rate=5s
        - --endpoint-name=knet-stress
        - --endpoint-namespace=knet-stress
          #- --serving-address=127.0.0.1
        - --serving-address=0.0.0.0:6443
        env:
        - name: KNET_STRESS_INSTANCE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: gcr.io/jetstack-josh/knet-stress:v0.1.0-alpha.1
        imagePullPolicy: Always
        name: knet-stress
        ports:
        - containerPort: 6443
          protocol: TCP
          name: web
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoExecute
        key: node-role.kubernetes.io/cilium
      serviceAccountName: knet-stress
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: knet-stress-2
  namespace: knet-stress
  labels:
    app: knet-stress
spec:
  selector:
    matchLabels:
      app: knet-stress
  template:
    metadata:
      labels:
        app: knet-stress
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "6443"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - args:
        - server
        - --connection-rate=5s
        - --endpoint-name=knet-stress
        - --endpoint-namespace=knet-stress
          #- --serving-address=127.0.0.1
        - --serving-address=0.0.0.0:6443
        env:
        - name: KNET_STRESS_INSTANCE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: gcr.io/jetstack-josh/knet-stress:v0.1.0-alpha.1
        imagePullPolicy: Always
        name: knet-stress
        ports:
        - containerPort: 6443
          protocol: TCP
          name: web
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoExecute
        key: node-role.kubernetes.io/cilium
      serviceAccountName: knet-stress
